# Generated by Django 2.2.9 on 2020-01-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramwrap', '0003_auto_20200116_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramauthorization',
            name='phone',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
