# Generated by Django 2.2.9 on 2020-01-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramwrap', '0004_auto_20200119_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauthorization',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
